---


name: "Dev Infra Build"


on:
  repository_dispatch:
    types: [ development-deploy-event ]
  
  push:
    branches:
      - development

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.DEV_REGION }}



    steps:

      - name: "Repository Checkout"
        uses: actions/checkout@v3


      - name: "Terraform installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: "terraform init"
        run: |
           terraform init \
               -backend-config="bucket=${{ secrets.DEV_S3_BUCKET }}" \
               -backend-config="key=terraform.tfstate" \
               -backend-config="region=${{ secrets.DEV_REGION  }}" \
               -backend-config="access_key=${{ secrets.DEV_ACCESS_KEY  }}" \
               -backend-config="secret_key=${{ secrets.DEV_SECRET_ACCESS_KEY  }}" \

      - name: Terraform fmt
        run: terraform fmt


      - name: Terraform validate
        run: terraform validate


      - name: Terraform plan
        run: terraform plan -var-file=dev.tfvars

      - name: Terraform apply
        run: |
           terraform apply \
              -auto-approve \
              -var-file=dev.tfvars




